Closed and Interactive Loop Eval Diagram. Data Model Benchmarks/Tests/Scenarios.
flatland-association/flatland-benchmarks pull request #21
Opened 2024-12-13 16:10 UTC by chenkins

## Changes

* Closed and Interactive Loop Eval Diagram. 
*  Data Model Benchmarks/Tests/Scenarios

## Related issues

Closes #178 

## Checklist

- [ ] Tests are included for relevant behavior changes.
- [ ] Documentation is added in the `docs` folder for relevant behavior changes. If you made important user-facing
  changes, describe them under the `[Unreleased]` tag in `CHANGELOG.md`.
- [ ] Technical guidelines listed in `CONTRIBUTING.md` are followed.

2025-02-07 13:12 UTC, chenkins commented on docs/img/readme/SystemContext.drawio.png
Discussion with @manuschn tenetatively add logos
* powergrid: RTE
* ATM: TU-Delft

2025-02-07 13:26 UTC, chenkins commented on docs/img/readme/Closed_and_Interactive_Loop_Eval.drawio.png
Discussion with @manuschn 
* harmonize UI with glossary: evaluation sub-module -> rec -> HMI

2025-02-07 13:29 UTC, chenkins commented on docs/img/readme/DataModel.drawio.png
Discussion with @manuschn 
* use generic trajectory 
* replace DomainValidationCampaign  by objective

2025-02-09 21:58 UTC, chenkins commented on docs/img/readme/Closed_and_Interactive_Loop_Eval.drawio.png
@manuschn do we need scenario driver which takes the role of production information state of the building block view?

2025-02-10 08:52 UTC, manuschn commented on docs/img/readme/Closed_and_Interactive_Loop_Eval.drawio.png
not necessarily for all use cases of the evaluator, but in general I think it makes sense to have both of them. let's discuss on with a whiteboard :)

2025-02-11 01:24 UTC, SergeCroise commented on README.md
> +| Validation Campaign | <ul><li>succeeded yes or no (iff all domain validation campaigns succeed)</li></ul>                                                  |
```suggestion
| Validation Campaign | <ul><li>succeeded yes or no (if all domain validation campaigns succeed)</li></ul>                                                  |
```

2025-02-11 01:30 UTC, SergeCroise commented on README.md
> +| Domain Expert Evaluator                     | anylyses scenario outcomes, either from FAB (FAB-internal evaluation) or Domain-Specific Evaluation System (FAB-external evaluation), or uploads scenar
```suggestion
| Domain Expert Evaluator                     | analyses scenario outcomes, either from FAB (FAB-internal evaluation) or Domain-Specific Evaluation System (FAB-external evaluation), or uploads scenario outcomes to FAB from FAB-external evaluations. Domain Expert Evaluator may interview Operators for evaluation. |
```

2025-02-11 01:48 UTC, SergeCroise commented on README.md
>  To participate, or even organize your own benchmarks or competitions, you don't need to install anything, you just need to sign in an instance of the platform (
line break before the opening parenthesis or after the closing parenthesis ?
(see the blank in the rendered markdown)

2025-02-11 01:54 UTC, SergeCroise commented on README.md
> +| FAB Web+Backend      | Manage scenarios for FAB-internal evaluation. Manage validation campgains and results for both FAB-internal and FAB-external evaluation.  |
```suggestion
| FAB Web+Backend      | Manage scenarios for FAB-internal evaluation. Manage validation campaings and results for both FAB-internal and FAB-external evaluation.  |
```

2025-02-11 02:14 UTC, SergeCroise commented on README.md
> +| Operator                                    | interacts with UI (issuing requests to based on information or action options from) either FAB (FAB-internal evaluation) or Domain-Specific Evaluation
```suggestion
| Operator                                    | interacts with UI (issuing requests based on information or action options) from either FAB (FAB-internal evaluation) or Domain-Specific Evaluation System (FAB-external evaluation).                                                                                 |
```

(feel free do modify or reject my proposal)

2025-02-12 10:37 UTC, chenkins commented on README.md
> +| Validation Campaign | <ul><li>succeeded yes or no (iff all domain validation campaigns succeed)</li></ul>                                                  |
if and only.

2025-03-07 17:14 UTC, chenkins commented on docs/img/readme/data_model.py
not up to date

2025-05-05 15:45 UTC, chenkins commented on docs/ARCHITECTURE.md
> +TODO only fetch from S3 and process or direct JSON upload of result? both?!
fix TODOs

2025-05-05 15:46 UTC, chenkins commented on docs/ARCHITECTURE.md
>  ![InformationFlow.drawio.png](./img/architecture/InformationFlow.drawio.png)
not up to date.

2025-05-08 13:57 UTC, Holzchopf commented
Some notes and thoughts that might be relevant when fine-tuning the data models:

- When do scenario/test scores come into existence (from API view)? Is it all in one bulk when the evaluation is done or could it be that scores are reported continuously? Latter would allow for a primitive live update (n.b. without the necessity to establish a connection between user and evaluator).
- Scenarios can exit with `SUCCESS` or `FAILURE`. Scores can be there but could be missing. On failure, the reason should be provided. Is `FAILURE` + scores a possible combination? I.e. when aborted due to threshold undercut?
  - Same goes for tests.
- If an evaluation is aborted, should the remaining scenarios be populated with NaN scores?
  - IMHO simplest would be to treat missing results as NaN, i.e. don't populate in database what hasn't been reported.
- Should NaN from "scenario failed" be equal (as in: treated equally) as NaN from "scenario not run because test aborted"?
  - E.g.: on submission detail page, NaN from a failed scenario could be displayed as NaN or something, while the rows for not run scenarios would simply be omitted.
  - Same for tests.
- A benchmark evaluation can be `WAITING`, `RUNNING` or `COMPLETE` - I guess it would be best to let the evaluator set this state?
- Should the aggregator functions be able to distinguish between "NaN from failed scenario" and "NaN from scenario not evaluated yet"?
  - E.g. when watching the live update, missing results do not necessarily mean the whole test/benchmark will fail.
- Should the aggregator functions be able to distinguish between "NaN from failed test" and "NaN from test not selected for evaluation"?
- Possible NaN treatments in aggregation:
  - Ignore (i.e. don't accumulate)
  - Assume 0
  - Fail parent test or benchmark with reason
- Should re-running an evaluation invalidate all previous results for that submission? I.e. when previously Test 1 was run, then the user choses to do a re-run with Test 2 - should Test 1 results disappear?

2025-05-09 11:55 UTC, chenkins commented on docs/img/readme/data_model.py
> +  sum_normalized_reward = df["normalized_reward"].sum()
Beware: 
pandas has [DataFram.sum](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sum.html) has one method with option `skipnabool, default True`
whereas numpy has two different methods [nansum](https://numpy.org/doc/stable/reference/generated/numpy.nansum.html) and [sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html)

2025-05-09 11:57 UTC, chenkins commented on docs/img/readme/data_model.py
> +  # - objective       -> (submission_id, "normalized_reward_all_tests")
use scenario, test and objective score instead?

2025-05-09 11:57 UTC, chenkins commented on docs/img/readme/data_model.py
> +  # TODO generalize to multiple submissions aka. scenario runs?
drop

2025-05-09 11:59 UTC, chenkins commented on docs/ARCHITECTURE.md
> +### &dagger; Interface 2: Redis result structure
remove

2025-05-09 12:00 UTC, chenkins commented on docs/ARCHITECTURE.md
> +### Interface 3: RabbitMQ
TODO update results direction

2025-05-09 12:00 UTC, chenkins commented on docs/ARCHITECTURE.md
> +### Interface 2: Scores API
Results API better?

2025-05-09 12:05 UTC, chenkins commented on docs/ARCHITECTURE.md
> +  }
extract to separate SUBMISSION API allowing for status update

2025-05-09 12:10 UTC, chenkins commented on docs/ARCHITECTURE.md
> +  }
Also: add publish flag.

2025-05-09 12:12 UTC, chenkins commented on docs/img/readme/data_model.py
> +  # TODO generalize the evaluation, the pd.DataFrame.from_records part
cleanup

2025-05-12 15:14 UTC, chenkins commented on docs/ARCHITECTURE.md
> +    string[] agg_field
Push-down into field structure?

2025-05-14 06:48 UTC, Holzchopf commented on docs/ARCHITECTURE.md
> +| `MEDIAN`             | no              | If one value is NaN, the median will be NaN, defaulting to 0. |
Why "defaulting to 0"? Shouldn't the default for `MEDIAN` be NaN as well?

2025-05-14 06:48 UTC, Holzchopf commented on docs/ARCHITECTURE.md
> +* `GET /benchmarks/{benchmark_id}/results`: by submission or by best test?
We could use URL parameters to flavor the endpoints, e.g.:

`GET /benchmarks/{benchmark_id}/tests?include=topSolution` would return tests with (the otherwise optional field) `topSolution` populated
`GET /benchmarks/{benchmark_id}/results?test={test_id}` would return results by test
`GET /benchmarks/{benchmark_id}/results?submission={submission_id}` would return results by submission

(Just drafted my thoughts. Naming and casing and options not set in stone yet)

2025-05-14 07:49 UTC, chenkins commented on docs/ARCHITECTURE.md
> +| `MEDIAN`             | no              | If one value is NaN, the median will be NaN, defaulting to 0. |
```suggestion
| `MEDIAN`             | no              | If one value is NaN, the median will be NaN, defaulting to NaN. |
```

2025-05-14 07:49 UTC, chenkins commented on docs/ARCHITECTURE.md
> +| `NANSUM`             | yes             | Sum over all non-NaN scores, defaulting to 0.                 |
```suggestion
| `NANSUM`             | yes             | Sum over all non-NaN scores, defaulting to NaN.                 |
```

2025-05-14 07:54 UTC, chenkins commented on docs/ARCHITECTURE.md
> +| `NANMEDIAN`          | no              | Median over all non-NaN scores, defaulting to 0.              |
numpy conventions:
```suggestion
| `SUM`                | yes             | If one value is NaN, the sum will be NaN. Empty sum defaulting to 0.                      |
| `NANSUM`             | yes             | Sum over all non-NaN scores. Empty sum defaulting to 0.               |
| `MEAN`               | yes             | If one value is NaN, the mean will be NaN. Empty mean defaulting to NaN.                   |
| `NANMEAN`            | yes             | Mean over all non-NaN scores, defaulting to 0.  Empty nanmean defaulting to NaN.              |
| `MEDIAN`             | no              | If one value is NaN, the median will be NaN, defaulting to 0. Empty median defaulting to NaN. |
| `NANMEDIAN`          | no              | Median over all non-NaN scores, defaulting to 0. Empty nanmedian defaulting to NaN.              |
```

2025-05-14 07:59 UTC, chenkins commented on docs/ARCHITECTURE.md
> +* `GET /benchmarks/{benchmark_id}/results`: by submission or by best test?
In my understanding:
> get list of tests with best submission per test

returns rows "test A | best score of test A of  all submissions"

whereas
> would return results by test

returns rows "submission X score" for {test_id}? For campaign overview, we need the former.

2025-05-14 12:09 UTC, chenkins commented on docs/ARCHITECTURE.md
> +* `GET /results/benchmark_group/{benchmark_group}`: get benchmarks with their best submission(s)
```suggestion
* `GET /results/benchmark_group/{benchmark_group}?num_submissions`: get benchmarks with their num_submissions best submission(s)
```

2025-05-14 12:09 UTC, chenkins commented on docs/ARCHITECTURE.md
> +Relational schema (multi-key-value based):
```suggestion
Relational schema (multi-key-value based, i.e. multiple "raw" scores per scenario possible):
```

2025-05-14 12:09 UTC, chenkins commented on docs/img/architecture/SystemContext.drawio.png
Add orchestrator part

2025-05-14 12:09 UTC, chenkins commented on docs/img/readme/sub-37557fc0-222e-4398-81d6-eade2892c9f6.csv
> +filename,Unnamed: 0,test_id,env_id,n_agents,x_dim,y_dim,n_cities,max_rail_pairs_in_city,n_envs_run,seed,grid_mode,max_rails_between_cities,malfunction_duration_min,malfunction_duration_max,malfunctio
drop, will be included in npm UTs

2025-05-14 12:09 UTC, chenkins commented on docs/img/readme/sub-37557fc0-222e-4398-81d6-eade2892c9f6.json
drop, will be included in npm UTs.

2025-05-14 12:09 UTC, chenkins commented on docs/ARCHITECTURE.md
> +Both, FAB-internal and FAB-external evaluation, can be closed-loop or interactive-loop (see above).
```suggestion
Both, FAB-internal and FAB-external evaluation, can be closed-loop or interactive-loop (see above). Offline-loop is always FAB-external.
```

2025-05-14 12:11 UTC, chenkins commented on docs/img/readme/data_model.py
drop, will be superseded by npm UTs

2025-05-14 12:20 UTC, chenkins commented on docs/img/readme/sub-37557fc0-222e-4398-81d6-eade2892c9f6.csv
drop, will be included in npm UTs

2025-05-14 12:21 UTC, chenkins commented on docs/ARCHITECTURE.md
> +## Runtime Scenario Closed Loop
what about s3?

2025-05-14 12:41 UTC, chenkins commented on docs/ARCHITECTURE.md
> +    string agg_field
Do we need to go back to array all the same? In case of weighted sum, having the same data in all scenarios or tests might be too restricting?

2025-05-14 14:40 UTC, Holzchopf approved these changes

2025-05-14 14:40 UTC, Holzchopf commented on docs/ARCHITECTURE.md
> +      "test_id": "00",
test_id would also be UUID here right?

2025-05-14 14:40 UTC, Holzchopf commented on docs/ARCHITECTURE.md
>  }
UUIDs for tests?

2025-05-14 14:40 UTC, Holzchopf commented on docs/ARCHITECTURE.md
> +    string agg_field
I think further development will show what's best. Let's be open to future changes.

2025-05-16 06:42 UTC, CleverManu requested changes
Minor adjustments, otherwise it looks good

2025-05-16 06:42 UTC, CleverManu commented on README.md
> +* closed-loop: the evaluation is carried without human in the loop (always for competition and benchmarks, optionally in campaign setting)
carried -> carried out (2x: here and below)

2025-05-16 06:42 UTC, CleverManu commented on README.md
>  ```shell
Is this a placeholder or could it be removed (since it is empty)?

2025-05-16 08:37 UTC, chenkins commented on README.md
> +* closed-loop: the evaluation is carried without human in the loop (always for competition and benchmarks, optionally in campaign setting)
```suggestion
* closed-loop: the evaluation is carried out without human in the loop (always for competition and benchmarks, optionally in campaign setting)
```

2025-05-16 08:38 UTC, chenkins commented on README.md
> +* interactive-loop: the evaluation is carried by a human Operator interacting with a UI, the results are uploaded automatically or/and manually
```suggestion
* interactive-loop: the evaluation is carried out by a human Operator interacting with a UI, the results are uploaded automatically or/and manually
```

2025-05-16 08:41 UTC, chenkins commented on README.md
>  ```shell
```suggestion
```shell
cd evaluation
docker compose  -f docker-compose-demo.yml up -d
```

2025-05-16 09:03 UTC, CleverManu commented on docs/ARCHITECTURE.md
> +    string agg_field
I think it would be good to have the option of weighted sums. I don't know yet how it will turn out, but I can think of multiple ways this feature would come in handy

2025-05-16 10:56 UTC, CleverManu commented on docs/ARCHITECTURE.md
> +    string agg_field
I agree to do it in steps and you're right, it might well be that we need the "apples and pears" case

2025-05-16 20:54 UTC, CleverManu approved these changes

2025-05-21 11:27 UTC, Holzchopf commented on docs/ARCHITECTURE.md
> +    uuid scenario_id PK
I just realized we have - a legacy from #94 - some tables with both `id` and `uuid` columns. To not mix different naming schemes, I'd recommend one or both of:

1. using `uuid` as part of the column name in UUID columns
```suggestion
    uuid benchmark_uuid PK, FK
    uuid test_uuid PK, FK
    uuid scenario_uuid PK
```

2. Adding a DB migration that drops the integer based id fields (unless of course if we need the more human readable IDs for debugging purposes).

2025-06-11 07:25 UTC, merged